[package]
name = "aes_from_scratch"
version = "0.1.0"
edition = "2024"

[lib]
name = "aes_from_scratch"
path = "aes/lib.rs"
[dependencies]
hex = "0.4.3"

[[bin]]
name = "square"
path = "attacks/square/mod.rs"